### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by MendelBak** [CakeCrusher/tech-int-cheat#10]
I cannot find this extension in the Chrome Extension Store. How do I install this?

**Comment by CakeCrusher** [comment]
@MendelBak 

Hey, thanks for your interest, its currently "pending approval" I will let you know once it is available on the chrome web store, I will only add a link to the read me. Expect for it to be available by Thursday.

**Comment by MendelBak** [comment]
Amazing! Thank you!

**Comment by CakeCrusher** [comment]
@MendelBak 
https://chrome.google.com/webstore/detail/tech-int-cheat/ldignaknonbhlddmhbfpempkbkdmbopo?hl=en&authuser=0
